- name: Calling NodeJS Role from Common
  ansible.builtin.include_role:
    name: common 
    tasks_from: nodejs
  

- name: generating the node modules
community.general.npm:
   path: /home/{{APPUSER}}/{{COMPONENT}}
